# Generated by Django 5.2.7 on 2025-11-17 13:51

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('document', 'Document'), ('image', 'Image'), ('audio', 'Audio'), ('video', 'Video'), ('code', 'Code'), ('data', 'Data'), ('archive', 'Archive'), ('other', 'Other')], max_length=20)),
                ('mime_types', models.JSONField(default=list, help_text='List of MIME types for this file type')),
                ('extensions', models.JSONField(default=list, help_text='List of file extensions')),
                ('parsers', models.JSONField(default=list, help_text='List of parser classes to use')),
                ('embedding_models', models.JSONField(default=list, help_text='List of embedding models to use')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AIAgent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('agent_type', models.CharField(choices=[('generic', 'Generic Assistant'), ('domain_specific', 'Domain Specific'), ('code_assistant', 'Code Assistant'), ('data_analyst', 'Data Analyst'), ('content_creator', 'Content Creator'), ('customer_support', 'Customer Support'), ('research_assistant', 'Research Assistant'), ('custom', 'Custom')], max_length=50)),
                ('model_provider', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('cohere', 'Cohere'), ('huggingface', 'HuggingFace'), ('local', 'Local Model')], default='openai', max_length=50)),
                ('model_name', models.CharField(default='gpt-3.5-turbo', max_length=100)),
                ('model_parameters', models.JSONField(default=dict, help_text='Model-specific parameters')),
                ('conversation_mode', models.CharField(choices=[('stateless', 'Stateless'), ('session', 'Session Based'), ('persistent', 'Persistent Memory'), ('contextual', 'Contextual Memory')], default='session', max_length=20)),
                ('context_window', models.IntegerField(default=4000, help_text='Maximum context window size')),
                ('memory_retention_days', models.IntegerField(default=30, help_text='Days to retain conversation memory')),
                ('system_prompt', models.TextField(help_text='System prompt for the agent')),
                ('user_prompt_template', models.TextField(blank=True, help_text='Template for user prompts')),
                ('max_documents', models.IntegerField(default=10, help_text='Maximum documents to retrieve')),
                ('similarity_threshold', models.FloatField(default=0.7, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('rate_limit_per_hour', models.IntegerField(default=100)),
                ('rate_limit_per_day', models.IntegerField(default=1000)),
                ('domain_keywords', models.JSONField(default=list, help_text='Keywords for domain-specific agents')),
                ('expertise_areas', models.JSONField(default=list, help_text='Areas of expertise')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_agents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('context', models.JSONField(default=dict, help_text='Conversation context and memory')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='knowledge_base.aiagent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('source_type', models.CharField(choices=[('gmail', 'Gmail'), ('google_drive', 'Google Drive'), ('salesforce', 'Salesforce'), ('file_upload', 'File Upload'), ('web_scraping', 'Web Scraping'), ('api', 'API Integration'), ('database', 'Database'), ('slack', 'Slack'), ('notion', 'Notion'), ('confluence', 'Confluence'), ('custom', 'Custom')], max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('error', 'Error'), ('syncing', 'Syncing')], default='active', max_length=20)),
                ('config', models.JSONField(default=dict, help_text='Configuration specific to the data source type')),
                ('credentials', models.JSONField(default=dict, help_text='Encrypted credentials for the data source')),
                ('auto_sync', models.BooleanField(default=True)),
                ('sync_frequency', models.IntegerField(default=24, help_text='Sync frequency in hours')),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_sources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.AddField(
            model_name='aiagent',
            name='data_sources',
            field=models.ManyToManyField(blank=True, help_text='Data sources to use', to='knowledge_base.datasource'),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('file_path', models.CharField(blank=True, max_length=1000)),
                ('file_size', models.BigIntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('raw_content', models.TextField(blank=True)),
                ('processed_content', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('processed', 'Processed'), ('error', 'Error'), ('soft_deleted', 'Soft Deleted')], default='pending', max_length=20)),
                ('processing_log', models.JSONField(default=list, help_text='Log of processing steps')),
                ('source_metadata', models.JSONField(default=dict, help_text='Metadata from the original source')),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('soft_deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('needs_processing', models.BooleanField(default=True, help_text='Whether this document needs to be processed')),
                ('processing_started_at', models.DateTimeField(blank=True, help_text='When processing started', null=True)),
                ('data_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='knowledge_base.datasource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
                ('file_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='knowledge_base.filetype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='aiagent',
            name='documents',
            field=models.ManyToManyField(blank=True, help_text='Documents to use', to='knowledge_base.document'),
        ),
        migrations.AddField(
            model_name='aiagent',
            name='file_types',
            field=models.ManyToManyField(blank=True, help_text='File types to include', to='knowledge_base.filetype'),
        ),
        migrations.CreateModel(
            name='KnowledgeBaseConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_embedding_model', models.CharField(default='sentence-transformers', max_length=100)),
                ('default_vector_store', models.CharField(default='chroma', max_length=100)),
                ('default_chunk_size', models.IntegerField(default=1000)),
                ('default_chunk_overlap', models.IntegerField(default=200)),
                ('document_retention_days', models.IntegerField(default=365, help_text='Days to keep documents')),
                ('conversation_retention_days', models.IntegerField(default=90, help_text='Days to keep conversations')),
                ('default_similarity_threshold', models.FloatField(default=0.7, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('max_search_results', models.IntegerField(default=20)),
                ('sync_notifications', models.BooleanField(default=True)),
                ('error_notifications', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kb_config', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=20)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(default=dict, help_text='Additional message metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cited_documents', models.ManyToManyField(blank=True, help_text='Documents cited in this message', to='knowledge_base.document')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='knowledge_base.conversation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserGoogleOAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credentials', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_oauth', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AgentUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tokens_used', models.IntegerField(default=0)),
                ('cost', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('response_time', models.FloatField(default=0, help_text='Response time in seconds')),
                ('request_data', models.JSONField(default=dict, help_text='Request metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_usage', to=settings.AUTH_USER_MODEL)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='knowledge_base.aiagent')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='knowledge_b_user_id_602d88_idx'), models.Index(fields=['agent', 'created_at'], name='knowledge_b_agent_i_06c3d7_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConnectedAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('twitter', 'Twitter'), ('facebook', 'Facebook')], max_length=20)),
                ('account_id', models.CharField(help_text='Platform-specific account ID', max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('profile_picture_url', models.URLField(blank=True, max_length=1000)),
                ('access_token', models.TextField(help_text='Encrypted access token')),
                ('refresh_token', models.TextField(blank=True, help_text='Encrypted refresh token')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('granted_scopes', models.JSONField(default=list, help_text='OAuth scopes granted')),
                ('permissions', models.JSONField(default=dict, help_text='Platform-specific permissions')),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connected_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'platform', 'account_id')},
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('chunk_index', models.IntegerField(default=0)),
                ('embeddings', models.JSONField(default=dict, help_text='Embeddings from different models')),
                ('metadata', models.JSONField(default=dict, help_text='Additional metadata for the chunk')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='knowledge_base.document')),
            ],
            options={
                'ordering': ['document', 'chunk_index'],
                'unique_together': {('document', 'chunk_index')},
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['user', 'status'], name='knowledge_b_user_id_a81fe6_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['data_source', 'created_at'], name='knowledge_b_data_so_8e7506_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='aiagent',
            unique_together={('user', 'name')},
        ),
    ]
