# Generated by Django 5.2.7 on 2025-11-25 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='connectedaccount',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='connectedaccount',
            name='business_id',
            field=models.UUIDField(blank=True, help_text='Business user ID for business-connected accounts', null=True),
        ),
        migrations.AlterField(
            model_name='connectedaccount',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connected_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='connectedaccount',
            constraint=models.CheckConstraint(condition=models.Q(('user__isnull', False), ('business_id__isnull', False), _connector='OR'), name='connected_account_user_or_business_required'),
        ),
        migrations.AddConstraint(
            model_name='connectedaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'platform', 'account_id'), name='unique_user_platform_account'),
        ),
        migrations.AddConstraint(
            model_name='connectedaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('business_id__isnull', False)), fields=('business_id', 'platform', 'account_id'), name='unique_business_platform_account'),
        ),
    ]
