# Generated by Django 5.2.7 on 2025-11-26 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0002_update_connected_account_for_business_users'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='connectedaccount',
            table='knowledge_base_connected_account',
        ),
    ]
