# Generated by Django 5.2.7 on 2025-11-17 13:51

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('knowledge_base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('logo_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('primary_color', models.CharField(default='#3b82f6', max_length=7)),
                ('secondary_color', models.CharField(default='#10b981', max_length=7)),
                ('font_family', models.CharField(default='Roboto', max_length=100)),
                ('brand_voice', models.TextField(blank=True)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('target_audience', models.TextField(blank=True)),
                ('business_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_brand', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_business_brand',
            },
        ),
        migrations.CreateModel(
            name='ContentCalendar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_profile_id', models.CharField(help_text='Business profile identifier', max_length=100)),
                ('title', models.CharField(help_text="Calendar title (e.g., 'December 2024')", max_length=255)),
                ('month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('year', models.IntegerField()),
                ('business_profile_data', models.JSONField(default=dict, help_text='Snapshot of business profile data used for generation')),
                ('generation_prompt', models.TextField(help_text='The prompt used to generate this calendar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_calendars', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_content_calendar',
                'ordering': ['-year', '-month', '-created_at'],
                'unique_together': {('user', 'business_profile_id', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='InstagramPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.TextField(blank=True)),
                ('media_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('posted', 'Posted'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('instagram_post_id', models.CharField(blank=True, max_length=255, null=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instagram_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_instagram_post',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialMediaPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_prompt', models.TextField(blank=True, help_text='Prompt used to generate the image')),
                ('layout_json', models.TextField(blank=True, help_text='JSON layout for programmatic rendering', null=True)),
                ('generated_image_url', models.URLField(blank=True, help_text='S3 URL of generated image', max_length=1000, null=True)),
                ('caption', models.TextField(help_text='Post caption')),
                ('hashtags', models.TextField(help_text='Post hashtags')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generating', 'Generating'), ('ready', 'Ready to Post'), ('refining', 'Refining'), ('publishing', 'Publishing'), ('published', 'Published'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('user_input', models.TextField(help_text='Original user request')),
                ('instagram_post_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_media_posts', to='api.businessbrand')),
                ('connected_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='knowledge_base.connectedaccount')),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='knowledge_base.conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_media_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_social_media_post',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentIdea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Short title/topic of the content idea', max_length=255)),
                ('description', models.TextField(help_text='Detailed description of the content idea')),
                ('content_type', models.CharField(choices=[('promo', 'Promotional'), ('educational', 'Educational'), ('user_generated', 'User Generated'), ('behind_scenes', 'Behind the Scenes'), ('testimonial', 'Testimonial'), ('holiday', 'Holiday')], max_length=50)),
                ('generation_prompt', models.TextField(help_text='The prompt to feed into the post generation endpoint')),
                ('scheduled_date', models.DateField(help_text='Planned date for this post')),
                ('scheduled_time', models.TimeField(blank=True, help_text='Planned time for this post', null=True)),
                ('status', models.CharField(choices=[('pending_approval', 'Needs Approval'), ('scheduled', 'Scheduled to Post'), ('published', 'Published')], default='pending_approval', max_length=50)),
                ('published_post_id', models.CharField(blank=True, help_text='Platform-specific post ID after publishing', max_length=255)),
                ('user_notes', models.TextField(blank=True, help_text='Additional notes from the user')),
                ('media_urls', models.JSONField(default=list, help_text='URLs of user-provided images/videos for this post')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('content_calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_ideas', to='api.contentcalendar')),
                ('generated_post', models.ForeignKey(blank=True, help_text='Reference to generated social media post', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.socialmediapost')),
            ],
            options={
                'db_table': 'api_content_idea',
                'ordering': ['scheduled_date', 'scheduled_time', 'created_at'],
            },
        ),
    ]
