# Generated by Django 5.2.7 on 2025-11-22 00:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_create_contentcalendar'),
        ('knowledge_base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediapost',
            name='business_id',
            field=models.UUIDField(blank=True, help_text='Business user ID for business-created posts', null=True),
        ),
        migrations.AlterField(
            model_name='socialmediapost',
            name='business_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_media_posts', to='api.businessbrand'),
        ),
        migrations.AlterField(
            model_name='socialmediapost',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_media_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='socialmediapost',
            constraint=models.CheckConstraint(condition=models.Q(('user__isnull', False), ('business_id__isnull', False), _connector='OR'), name='api_social_media_post_user_or_business_required'),
        ),
    ]
