import { Shape, ColorPalette } from "@/types/Canvas";

export const generateTemplate = (
  width: number,
  height: number,
  colorPalette: ColorPalette
): Shape[] => {
  return [
    {
      id: "triangle-tl",
      type: "triangle",
      x: 0,
      y: 0,
      color: colorPalette.primary,
      points: [
        { x: 0, y: 0 },
        { x: 200, y: 0 },
        { x: 0, y: 200 },
      ],
    },
    {
      id: "triangle-tr",
      type: "triangle",
      x: width - 200,
      y: 0,
      color: colorPalette.primary,
      points: [
        { x: width, y: 0 },
        { x: width, y: 200 },
        { x: width - 200, y: 0 },
      ],
    },
    {
      id: "triangle-bl",
      type: "triangle",
      x: 0,
      y: height - 200,
      color: colorPalette.primary,
      points: [
        { x: 0, y: height },
        { x: 0, y: height - 200 },
        { x: 200, y: height },
      ],
    },
    {
      id: "triangle-br",
      type: "triangle",
      x: width - 200,
      y: height - 200,
      color: colorPalette.primary,
      points: [
        { x: width, y: height },
        { x: width - 200, y: height },
        { x: width, y: height - 200 },
      ],
    },
    {
      id: "cross-1",
      type: "cross",
      x: 300,
      y: 250,
      width: 80,
      color: colorPalette.secondary,
      strokeWidth: 4,
      rotation: 15,
    },
    {
      id: "cross-2",
      type: "cross",
      x: width - 350,
      y: 400,
      width: 100,
      color: colorPalette.accent,
      strokeWidth: 5,
      rotation: -20,
    },
    {
      id: "cross-3",
      type: "cross",
      x: 250,
      y: height - 350,
      width: 90,
      color: colorPalette.secondary,
      strokeWidth: 4,
      rotation: 45,
    },
    {
      id: "cross-4",
      type: "cross",
      x: width / 2 - 100,
      y: 180,
      width: 60,
      color: colorPalette.accent,
      strokeWidth: 3,
      rotation: 30,
    },
    {
      id: "cross-5",
      type: "cross",
      x: width / 2 + 150,
      y: height / 2 - 50,
      width: 70,
      color: colorPalette.secondary,
      strokeWidth: 4,
      rotation: -45,
    },
    {
      id: "cross-6",
      type: "cross",
      x: 180,
      y: height / 2 + 100,
      width: 65,
      color: colorPalette.accent,
      strokeWidth: 3,
      rotation: 60,
    },
    {
      id: "cross-7",
      type: "cross",
      x: width - 250,
      y: height - 280,
      width: 75,
      color: colorPalette.secondary,
      strokeWidth: 4,
      rotation: -30,
    },
    {
      id: "cross-8",
      type: "cross",
      x: 400,
      y: 120,
      width: 40,
      color: colorPalette.accent,
      strokeWidth: 2,
      rotation: 0,
    },
    {
      id: "cross-9",
      type: "cross",
      x: width - 180,
      y: 300,
      width: 35,
      color: colorPalette.secondary,
      strokeWidth: 2,
      rotation: 25,
    },
    {
      id: "cross-10",
      type: "cross",
      x: 120,
      y: 400,
      width: 45,
      color: colorPalette.accent,
      strokeWidth: 3,
      rotation: -15,
    },
    {
      id: "cross-11",
      type: "cross",
      x: width / 2 + 80,
      y: height - 200,
      width: 50,
      color: colorPalette.secondary,
      strokeWidth: 3,
      rotation: 35,
    },
    {
      id: "cross-12",
      type: "cross",
      x: width - 400,
      y: height - 150,
      width: 42,
      color: colorPalette.accent,
      strokeWidth: 2,
      rotation: -50,
    },
  ];
};

