# Generated by Django 5.2.7 on 2025-11-17 13:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateGroupModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grp_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique group identifier', unique=True)),
                ('chat_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique chat session identifier', unique=True)),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique session identifier', unique=True)),
                ('agent_labels', models.JSONField(default=list, help_text="List of agent labels (e.g., ['Maavi', 'Lawanya'])")),
                ('name', models.CharField(help_text='User-provided group name', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the group was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the group was last updated')),
                ('user', models.ForeignKey(help_text='Owner of this group', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agent Group',
                'verbose_name_plural': 'Agent Groups',
            },
        ),
    ]
